#!/bin/bash

mkdir -p  ~/.local/bin
cp ytb  ~/.local/bin
if ! grep 'export PATH="$HOME/.local/bin:$PATH' ~/.bashrc; then
	echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
fi
chmod ug+rwx ~/.local/bin/ytb
echo 'Installation done!'
